const MIN_SIZE_FOR_LARGE_SCREEN = 1279;
const MAX_SIZE_FOR_MEDIUM_SCREEN = 1278;
const MIN_SIZE_FOR_MEDIUM_SCREEN = 767;
const MAX_SIZE_FOR_SMALL_SCREEN = 766;

const MOVIES_AMOUNT_LARGE = 16;
const MOVIES_AMOUNT_MEDIUM = 8;
const MOVIES_AMOUNT_SMALL = 5;

const MOVIES_MORE_LARGE = 4;
const MOVIES_MORE_SMALL = 2;

const MAX_FILM_DURATION = 40;

export {
  MIN_SIZE_FOR_LARGE_SCREEN,
  MAX_SIZE_FOR_MEDIUM_SCREEN,
  MIN_SIZE_FOR_MEDIUM_SCREEN,
  MAX_SIZE_FOR_SMALL_SCREEN,
  MOVIES_AMOUNT_LARGE,
  MOVIES_AMOUNT_MEDIUM,
  MOVIES_AMOUNT_SMALL,
  MOVIES_MORE_LARGE,
  MOVIES_MORE_SMALL,
  MAX_FILM_DURATION,
};
